# Generated by Django 4.2.7 on 2023-11-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orendary',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Primischennya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('area', models.FloatField()),
                ('rent_cost_per_sqm', models.FloatField()),
                ('floor', models.IntegerField()),
                ('phone_in_room', models.BooleanField()),
                ('decoration', models.CharField(choices=[('ordinary', 'Звичайне'), ('improved', 'Поліпшене'), ('euro', 'Євро')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('purpose', models.CharField(choices=[('office', 'Офіс'), ('kiosk', 'Кіоск'), ('warehouse', 'Склад')], max_length=10)),
                ('orendary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AFR.orendary')),
                ('primischennya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AFR.primischennya')),
            ],
        ),
    ]
